notes: |
order: 10
status: ready
context:
  menu:
    modifier: main
    items:
      - label: Samenwerkingen
        active: true
      - label: Acties overzicht
      - label: Notificatie overzicht
  appheading:
    title: Aanvraag Bomenkappen Genooyerweg 37
    subtitle: Samenwerkings overzicht
  submenu:
    modifier: sub
    items:
      - label: Documenten
      - label: Ketenpartners
      - label: Notificaties
      - label: Actieverzoeken
        active: true
  tabNav:
    tabs:
      - label: Ontvangen
        url: '#'
        modifiers: disabled
      - label: Verzonden
        url: '#'
        modifiers: active
  definitionList:
    modifier: dso-columns dso-2-columns
    dsoColumns: true
    definitions:
      - term: "Status:"
        descriptions:
          - description: Open
      - term: "Verzonden aan:"
        descriptions:
          - description: Gemeente Den Haag
      - term: "Datum:"
        descriptions:
          - description: 20-10-2020
  formContent:
    formModifier: dso-single-page
    fieldsets:
    - legend: Intrekken actieverzoek
      groups:
      - id: actieverzoekMelding
        inputType: textarea
        label: Toelichting intrekken
        rows: 6
    buttons:
    - type: submit
      modifier: primary
      label: Actieverzoek intrekken
